# Generated by Django 5.1.2 on 2024-11-04 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_quantitativomateriais'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quantitativomateriais',
            old_name='qtdApostilas',
            new_name='apostilas',
        ),
        migrations.RenameField(
            model_name='quantitativomateriais',
            old_name='qtdDissertacoes',
            new_name='dissertacoes',
        ),
        migrations.RenameField(
            model_name='quantitativomateriais',
            old_name='qtdJornais',
            new_name='jornais',
        ),
        migrations.RenameField(
            model_name='quantitativomateriais',
            old_name='qtdLivros',
            new_name='livros',
        ),
        migrations.RenameField(
            model_name='quantitativomateriais',
            old_name='qtdTCCs',
            new_name='tccs',
        ),
        migrations.RenameField(
            model_name='quantitativomateriais',
            old_name='qtdTeses',
            new_name='teses',
        ),
    ]
