# Generated by Django 5.2.6 on 2025-09-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_tcc'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantitativoMateriais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livros', models.IntegerField()),
                ('tccs', models.IntegerField()),
                ('dissertacoes', models.IntegerField()),
                ('teses', models.IntegerField()),
                ('apostilas', models.IntegerField()),
                ('jornais', models.IntegerField()),
            ],
        ),
    ]
