# Generated by Django 5.2.6 on 2025-09-17 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_quantitativomateriais'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuantitativoMateriais',
        ),
    ]
